-- V1__esquema_inicial.sql — Fase 1. Esquema completo (reset, sin baseline del modelo anterior).
-- Referencia: docs/arquitectura/fase-1-modelo.md y ADR 0001-0006. Las migraciones aplicadas no se editan:
-- cualquier cambio va en un V{n}__descripcion.sql nuevo.

CREATE TABLE parqueadero (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        varchar(80)  NOT NULL,
    zona_horaria  varchar(40)  NOT NULL DEFAULT 'America/Bogota',
    creado_en     timestamptz  NOT NULL DEFAULT now()
);

-- Administradores del panel. Hoy hay uno, creado al arrancar desde ADMIN_USERNAME/ADMIN_PASSWORD
-- (solo se guarda el hash BCrypt). Mismo bloqueo por intentos que los usuarios.
CREATE TABLE administrador (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario            varchar(50)  NOT NULL,
    password_hash      varchar(60)  NOT NULL,
    intentos_fallidos  integer      NOT NULL DEFAULT 0,
    bloqueado_hasta    timestamptz,
    creado_en          timestamptz  NOT NULL DEFAULT now(),
    actualizado_en     timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT uq_administrador_usuario  UNIQUE (usuario),
    CONSTRAINT ck_administrador_intentos CHECK (intentos_fallidos >= 0)
);

CREATE TABLE cupo (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parqueadero_id  bigint       NOT NULL REFERENCES parqueadero (id),
    codigo          varchar(10)  NOT NULL,
    tipo_vehiculo   varchar(10)  NOT NULL,
    activo          boolean      NOT NULL DEFAULT true,
    creado_en       timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT ck_cupo_tipo   CHECK (tipo_vehiculo IN ('CARRO', 'MOTO')),
    CONSTRAINT uq_cupo_codigo UNIQUE (parqueadero_id, codigo)
);

CREATE TABLE usuario (
    id                           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parqueadero_id               bigint       NOT NULL REFERENCES parqueadero (id),
    cupo_id                      bigint       REFERENCES cupo (id),
    telefono                     varchar(15)  NOT NULL,
    nombre                       varchar(50)  NOT NULL,
    apellido                     varchar(50)  NOT NULL,
    estado                       varchar(12)  NOT NULL DEFAULT 'VENCIDO',
    suspendido_motivo            varchar(200),
    pin_hash                     varchar(60),
    codigo_validacion_hash       varchar(60),
    codigo_validacion_expira_en  timestamptz,
    validado_en                  timestamptz,
    intentos_fallidos            integer      NOT NULL DEFAULT 0,
    bloqueado_hasta              timestamptz,
    consentimiento_datos_en      timestamptz,
    consentimiento_version       varchar(20),
    simulado                     boolean      NOT NULL DEFAULT false,
    dado_de_baja_en              timestamptz,
    creado_en                    timestamptz  NOT NULL DEFAULT now(),
    actualizado_en               timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT ck_usuario_estado     CHECK (estado IN ('ACTIVO', 'VENCIDO', 'SUSPENDIDO')),
    CONSTRAINT ck_usuario_telefono   CHECK (telefono ~ '^\+?[0-9]{7,15}$'),
    CONSTRAINT ck_usuario_intentos   CHECK (intentos_fallidos >= 0),
    CONSTRAINT ck_usuario_suspension CHECK (estado <> 'SUSPENDIDO' OR suspendido_motivo IS NOT NULL),
    -- Validado implica PIN y consentimiento (Ley 1581).
    CONSTRAINT ck_usuario_validado   CHECK (validado_en IS NULL
                                            OR (pin_hash IS NOT NULL AND consentimiento_datos_en IS NOT NULL)),
    -- Dado de baja implica cupo liberado.
    CONSTRAINT ck_usuario_baja       CHECK (dado_de_baja_en IS NULL OR cupo_id IS NULL)
);
-- Unicidad de negocio solo entre usuarios reales y vigentes: deja convivir bajas e histórico simulado.
CREATE UNIQUE INDEX uq_usuario_telefono_vigente ON usuario (telefono)
    WHERE dado_de_baja_en IS NULL AND NOT simulado;
CREATE UNIQUE INDEX uq_usuario_cupo_vigente ON usuario (cupo_id)
    WHERE cupo_id IS NOT NULL AND dado_de_baja_en IS NULL AND NOT simulado;
CREATE INDEX ix_usuario_parqueadero_estado ON usuario (parqueadero_id, estado)
    WHERE dado_de_baja_en IS NULL;

CREATE TABLE vehiculo (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     bigint       NOT NULL REFERENCES usuario (id),
    placa          varchar(10)  NOT NULL,
    tipo_vehiculo  varchar(10)  NOT NULL,
    carroceria     varchar(15),
    color          varchar(30)  NOT NULL,
    marca          varchar(40),
    activo         boolean      NOT NULL DEFAULT true,
    simulado       boolean      NOT NULL DEFAULT false,
    creado_en      timestamptz  NOT NULL DEFAULT now(),
    -- Placa normalizada por el backend (mayúsculas, sin espacios ni guiones). El formato colombiano
    -- exacto por tipo (CARRO AAA999, MOTO AAA99 / AAA99A) se valida en el servicio.
    CONSTRAINT ck_vehiculo_placa      CHECK (placa ~ '^[A-Z0-9]{5,7}$'),
    CONSTRAINT ck_vehiculo_tipo       CHECK (tipo_vehiculo IN ('CARRO', 'MOTO')),
    CONSTRAINT ck_vehiculo_carroceria CHECK (carroceria IN ('SEDAN', 'HATCHBACK', 'SUV', 'PICKUP', 'VAN',
                                                            'COUPE', 'OTRO')),
    -- Carrocería obligatoria para carro; las motos no la usan en Fase 1.
    CONSTRAINT ck_vehiculo_carroceria_tipo CHECK ((tipo_vehiculo = 'CARRO' AND carroceria IS NOT NULL)
                                                  OR (tipo_vehiculo = 'MOTO' AND carroceria IS NULL))
);
CREATE UNIQUE INDEX uq_vehiculo_placa_activa ON vehiculo (placa)
    WHERE activo AND NOT simulado;
CREATE UNIQUE INDEX uq_vehiculo_usuario_activo ON vehiculo (usuario_id)
    WHERE activo AND NOT simulado;
CREATE INDEX ix_vehiculo_usuario ON vehiculo (usuario_id);

CREATE TABLE tarifa (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parqueadero_id  bigint       NOT NULL REFERENCES parqueadero (id),
    tipo_vehiculo   varchar(10)  NOT NULL,
    valor_mensual   integer      NOT NULL,
    vigente_desde   date         NOT NULL,
    creado_en       timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT ck_tarifa_tipo  CHECK (tipo_vehiculo IN ('CARRO', 'MOTO')),
    CONSTRAINT ck_tarifa_valor CHECK (valor_mensual > 0),
    -- Tarifa vigente en F = la de mayor vigente_desde <= F. Este índice sirve a esa búsqueda.
    CONSTRAINT uq_tarifa_vigencia UNIQUE (parqueadero_id, tipo_vehiculo, vigente_desde)
);

CREATE TABLE pago (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id          bigint        NOT NULL REFERENCES usuario (id),
    tarifa_id           bigint        NOT NULL REFERENCES tarifa (id),
    periodo_inicio      date          NOT NULL,
    periodo_fin         date          NOT NULL,
    monto_esperado      integer       NOT NULL,
    monto_ocr           integer,
    fecha_pago_ocr      date,
    ocr_estado          varchar(10)   NOT NULL,
    ocr_datos           jsonb,
    monto_confirmado    integer,
    estado              varchar(10)   NOT NULL DEFAULT 'PENDIENTE',
    motivo_rechazo      varchar(200),
    observacion         varchar(200),
    registrado_por      varchar(10)   NOT NULL,
    comprobante_ruta    varchar(255),
    comprobante_tipo    varchar(30),
    comprobante_sha256  varchar(64),
    posible_duplicado   boolean       NOT NULL DEFAULT false,
    revisado_en         timestamptz,
    simulado            boolean       NOT NULL DEFAULT false,
    creado_en           timestamptz   NOT NULL DEFAULT now(),
    actualizado_en      timestamptz   NOT NULL DEFAULT now(),
    CONSTRAINT ck_pago_estado        CHECK (estado IN ('PENDIENTE', 'APROBADO', 'RECHAZADO')),
    CONSTRAINT ck_pago_ocr_estado    CHECK (ocr_estado IN ('EXITOSO', 'PARCIAL', 'FALLIDO', 'NO_APLICA')),
    CONSTRAINT ck_pago_registrado    CHECK (registrado_por IN ('USUARIO', 'ADMIN')),
    CONSTRAINT ck_pago_periodo       CHECK (periodo_fin >= periodo_inicio),
    CONSTRAINT ck_pago_montos        CHECK (monto_esperado >= 0
                                            AND (monto_ocr IS NULL OR monto_ocr >= 0)
                                            AND (monto_confirmado IS NULL OR monto_confirmado >= 0)),
    CONSTRAINT ck_pago_revision      CHECK (estado = 'PENDIENTE' OR revisado_en IS NOT NULL),
    CONSTRAINT ck_pago_aprobado      CHECK (estado <> 'APROBADO' OR monto_confirmado IS NOT NULL),
    CONSTRAINT ck_pago_rechazado     CHECK (estado <> 'RECHAZADO' OR motivo_rechazo IS NOT NULL),
    CONSTRAINT ck_pago_comprobante   CHECK (comprobante_ruta IS NULL
                                            OR (comprobante_sha256 IS NOT NULL AND comprobante_tipo IS NOT NULL)),
    CONSTRAINT ck_pago_sha256        CHECK (comprobante_sha256 IS NULL OR comprobante_sha256 ~ '^[0-9a-f]{64}$')
);
-- Un solo pago pendiente por usuario real.
CREATE UNIQUE INDEX uq_pago_pendiente_usuario ON pago (usuario_id)
    WHERE estado = 'PENDIENTE' AND NOT simulado;
-- No se aprueban dos pagos para el mismo periodo.
CREATE UNIQUE INDEX uq_pago_aprobado_periodo ON pago (usuario_id, periodo_inicio)
    WHERE estado = 'APROBADO';
-- Último periodo aprobado (cálculo del siguiente periodo y del vencimiento).
CREATE INDEX ix_pago_usuario_periodo_fin ON pago (usuario_id, periodo_fin DESC);
-- Bandeja de revisión del admin.
CREATE INDEX ix_pago_estado_creado ON pago (estado, creado_en DESC);
CREATE INDEX ix_pago_sha256 ON pago (comprobante_sha256) WHERE comprobante_sha256 IS NOT NULL;

CREATE TABLE puerta (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parqueadero_id  bigint       NOT NULL REFERENCES parqueadero (id),
    nombre          varchar(50)  NOT NULL,
    -- abierta = abierta_hasta > now(). No hace falta un job de cierre.
    abierta_hasta   timestamptz,
    actualizado_en  timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE camara (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parqueadero_id  bigint        NOT NULL REFERENCES parqueadero (id),
    nombre          varchar(50)   NOT NULL,
    url             varchar(200),
    activa          boolean       NOT NULL DEFAULT true,
    simulada        boolean       NOT NULL DEFAULT true,
    creado_en       timestamptz   NOT NULL DEFAULT now()
);

CREATE TABLE evento_acceso (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parqueadero_id  bigint        NOT NULL REFERENCES parqueadero (id),
    placa_leida     varchar(15)   NOT NULL,
    vehiculo_id     bigint        REFERENCES vehiculo (id),
    usuario_id      bigint        REFERENCES usuario (id),
    camara_id       bigint        REFERENCES camara (id),
    puerta_id       bigint        REFERENCES puerta (id),
    tipo            varchar(7)    NOT NULL,
    tipo_inferido   boolean       NOT NULL DEFAULT true,
    resultado       varchar(9)    NOT NULL,
    motivo          varchar(25),
    origen          varchar(15)   NOT NULL,
    observacion     varchar(200),
    ocurrido_en     timestamptz   NOT NULL,
    registrado_en   timestamptz   NOT NULL DEFAULT now(),
    simulado        boolean       NOT NULL DEFAULT false,
    CONSTRAINT ck_evento_tipo      CHECK (tipo IN ('ENTRADA', 'SALIDA')),
    CONSTRAINT ck_evento_resultado CHECK (resultado IN ('PERMITIDO', 'DENEGADO')),
    CONSTRAINT ck_evento_origen    CHECK (origen IN ('CAMARA', 'APP_USUARIO', 'MANUAL_ADMIN')),
    -- YA_DENTRO: ENTRADA explícita de un vehículo cuyo último evento permitido ya es una ENTRADA.
    CONSTRAINT ck_evento_motivo    CHECK (motivo IN ('PLACA_DESCONOCIDA', 'USUARIO_VENCIDO', 'USUARIO_SUSPENDIDO',
                                                     'USUARIO_DE_BAJA', 'SIN_CUPO', 'TIPO_CUPO_DISTINTO',
                                                     'FORZADO_ADMIN', 'SALIDA_CON_DEUDA', 'YA_DENTRO')),
    CONSTRAINT ck_evento_denegado  CHECK (resultado = 'PERMITIDO' OR motivo IS NOT NULL),
    -- Sin vehículo identificado solo cabe placa desconocida o apertura forzada por el admin.
    -- (motivo IS NOT NULL es necesario: NULL IN (...) da NULL y el CHECK lo dejaría pasar).
    CONSTRAINT ck_evento_vehiculo  CHECK (vehiculo_id IS NOT NULL
                                          OR (motivo IS NOT NULL AND motivo IN ('PLACA_DESCONOCIDA', 'FORZADO_ADMIN')))
);
-- Inferencia ENTRADA/SALIDA, anti-rebote y ocupación: último evento por vehículo.
CREATE INDEX ix_evento_vehiculo_ocurrido ON evento_acceso (vehiculo_id, ocurrido_en DESC);
-- Listados del admin y series temporales de analítica.
CREATE INDEX ix_evento_parqueadero_ocurrido ON evento_acceso (parqueadero_id, ocurrido_en DESC);
-- Historial del usuario en la app.
CREATE INDEX ix_evento_usuario_ocurrido ON evento_acceso (usuario_id, ocurrido_en DESC);
